config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :v1 do
      resources :fetchers
      match 'room' => 'fetchers#room', via: [:get, :post], :defaults => { :format => :json }
    end
  end

  root to: 'visitors#index'
end

app/models/fetcher.rb
class Fetcher < ActiveRecord::Base

	# returns the property data hash
	# input => property JSON
	# output => Hash
	def parse(property)
		json_content = JSON.parse(property)
    property_data = json_content["properties"]
    room_data = Hash.new

    property_data.each do |property|
      property_hash = build_formatted_property_hash(property)
      room_data = {'room' => property_hash}
    end

    room_data
	end

	# builds the property hash with correct set of keys as per structure provided
	# output => Hash
	def build_formatted_property_hash(property)
    property_hash = Hash.new
    property_hash = 
      {
        "address"=> property["property_adress"], 
        "apartment_number"=> property["apartment_no"],
        "postal_code"=> property["zip_code"],
        "city"=> property["town"],
        "country"=> property["country"],
        "description"=> property["property_description"],
        "number_of_bedrooms"=> property["bedrooms_no"],
        "max_guests"=> property["max_people"],
        "internal_id"=> property["source_id"]
      }
  end

	private

	def self.get_properties
		property_data = '{"properties":[{"property_adress":"72 Central Park W","apartment_no":"7","zip_code":"8002","town":"Zurich","country":"Swiss","property_description":"fake description of the property","bedrooms_no":"1","max_people":"2","source_id":"68123"}]}'
	end	
end

app/controllers/api/v1/fetchers_controller.rb
require 'json'

class Api::V1::FetchersController < ApplicationController

  respond_to :json

  # GET /api/v1/room
  def room
    respond_with Fetcher.new.parse(Fetcher.get_properties)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fetchers_helper.rb
module FetchersHelper
end

app/views/fetchers/_form.html.haml
= form_for @fetcher do |f|
  - if @fetcher.errors.any?
    #error_explanation
      %h2= "#{pluralize(@fetcher.errors.count, "error")} prohibited this fetcher from being saved:"
      %ul
        - @fetcher.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/fetchers/edit.html.haml
%h1 Editing fetcher

= render 'form'

= link_to 'Show', @fetcher
\|
= link_to 'Back', fetchers_path

app/views/fetchers/index.html.haml
%h1 Listing fetchers

%table
  %tr
    %th
    %th
    %th

  - @fetchers.each do |fetcher|
    %tr
      %td= link_to 'Show', fetcher
      %td= link_to 'Edit', edit_fetcher_path(fetcher)
      %td= link_to 'Destroy', fetcher, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Fetcher', new_fetcher_path

app/views/fetchers/new.html.haml
%h1 New fetcher

= render 'form'

= link_to 'Back', fetchers_path

app/views/fetchers/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_fetcher_path(@fetcher)
\|
= link_to 'Back', fetchers_path

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Property Parser'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Property Parser'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>